/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package carsrentalmanagementsystem;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class AddCars extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddCars
     */
    public AddCars() {
        initComponents();

        CarRentals cr = new CarRentals();

        txtRegDate.setText(cr.setDate() + " " + cr.setTime());
    }

    void reset() {
        txt_brand.setText("");
        txt_make.setText("");
        txt_color.setText("");
        txt_passengers.setText("");
        txt_rentalPrice.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_brand = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_make = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_color = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_passengers = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_rentalPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtRegDate = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        add_new_car_btn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Add New Cars");
        setToolTipText("");
        setMinimumSize(new java.awt.Dimension(533, 362));
        setPreferredSize(new java.awt.Dimension(533, 362));

        jPanel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 48)); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 50));

        jLabel8.setFont(new java.awt.Font("Poppins Light", 1, 24)); // NOI18N
        jLabel8.setText("Register Cars");
        jPanel2.add(jLabel8);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel7.setLayout(new java.awt.BorderLayout(10, 0));

        jPanel1.setLayout(new java.awt.GridLayout(0, 2, 5, 5));

        jLabel3.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Brand:");
        jLabel3.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.add(jLabel3);

        txt_brand.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txt_brand.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_brand.setToolTipText("E.g. Toyota");
        jPanel1.add(txt_brand);

        jLabel10.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Make:");
        jLabel10.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.add(jLabel10);

        txt_make.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txt_make.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_make.setToolTipText("E.g. Probox, Filder");
        jPanel1.add(txt_make);

        jLabel4.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Color:");
        jLabel4.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.add(jLabel4);

        txt_color.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txt_color.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_color.setToolTipText("E.g. White, Grey, Blue");
        jPanel1.add(txt_color);

        jLabel6.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Passengers:");
        jLabel6.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.add(jLabel6);

        txt_passengers.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txt_passengers.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_passengers.setToolTipText("E.g. White, Grey, Blue");
        jPanel1.add(txt_passengers);

        jLabel5.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Rental Price:");
        jLabel5.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.add(jLabel5);

        txt_rentalPrice.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txt_rentalPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(txt_rentalPrice);

        jLabel7.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Date of Purchase:");
        jLabel7.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.add(jLabel7);

        txtRegDate.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        txtRegDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtRegDate.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.add(txtRegDate);

        jPanel7.add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setMinimumSize(new java.awt.Dimension(200, 39));
        jPanel3.setPreferredSize(new java.awt.Dimension(10, 300));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel12.setPreferredSize(new java.awt.Dimension(10, 117));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel12, java.awt.BorderLayout.LINE_START);

        jPanel13.setPreferredSize(new java.awt.Dimension(10, 117));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel13, java.awt.BorderLayout.LINE_END);

        jPanel7.add(jPanel3, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel9.setPreferredSize(new java.awt.Dimension(20, 334));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel9, java.awt.BorderLayout.LINE_END);

        jPanel4.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 40, 10));

        add_new_car_btn.setFont(new java.awt.Font("Poppins Light", 1, 18)); // NOI18N
        add_new_car_btn.setText("Register");
        add_new_car_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_new_car_btnActionPerformed(evt);
            }
        });
        jPanel4.add(add_new_car_btn);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_new_car_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_new_car_btnActionPerformed
        // TODO add your handling code here:

        CarRentals cr = new CarRentals();
        String brand = txt_brand.getText();
        String make = txt_make.getText();
        String color = txt_color.getText();
        String passengers = txt_passengers.getText();
        String date = cr.setDate() + " " + cr.setTime();
        String rentalPrice = txt_rentalPrice.getText();
        if (brand.equals("") || rentalPrice.equals("") || make.equals("") || color.equals("") ||passengers.equals("")|| rentalPrice.equals("")) {
            JOptionPane.showMessageDialog(this, "One of the Fields is empty", "Car Rental Services - Error Message", JOptionPane.ERROR_MESSAGE);
        } else {
            cr.addCars(brand, make, color,passengers, date, rentalPrice);
            reset();
        }
                this.dispose();


    }//GEN-LAST:event_add_new_car_btnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_new_car_btn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel txtRegDate;
    private javax.swing.JTextField txt_brand;
    private javax.swing.JTextField txt_color;
    private javax.swing.JTextField txt_make;
    private javax.swing.JTextField txt_passengers;
    private javax.swing.JTextField txt_rentalPrice;
    // End of variables declaration//GEN-END:variables
}
