/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package carsrentalmanagementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ManageEmp extends javax.swing.JInternalFrame {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    String query;

    DefaultTableModel model;
    CarRentals cr;

    /**
     * Creates new form ManageEmp
     */
    public ManageEmp() {
        initComponents();

        model = (DefaultTableModel) tbl_emp.getModel();
        getAllEmpRecords();
        rbtn_male.setSelected(true);

        cr = new CarRentals();
        txt_regDate.setText(cr.setDate() + " " + cr.setTime());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_empId = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        btn_viewbyId = new javax.swing.JButton();
        btn_viewAll = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        btn_add = new javax.swing.JButton();
        btn_remove = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txt_empId1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        rbtn_male = new javax.swing.JRadioButton();
        rbtn_female = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txt_phone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_regDate = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_emp = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Manage Employees");
        setMinimumSize(new java.awt.Dimension(974, 690));
        setPreferredSize(new java.awt.Dimension(974, 690));
        getContentPane().setLayout(new java.awt.BorderLayout(10, 10));

        jLabel1.setFont(new java.awt.Font("Poppins Light", 1, 24)); // NOI18N
        jLabel1.setText("Manage Employees");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(10, 331));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel3.setText("Manage Employees");
        jPanel3.add(jLabel3);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setPreferredSize(new java.awt.Dimension(10, 331));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 558, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel5.setLayout(new java.awt.GridLayout(0, 2, 10, 0));

        jPanel6.setLayout(new java.awt.BorderLayout(5, 5));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Car by Id", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins Light", 1, 12))); // NOI18N
        jPanel7.setPreferredSize(new java.awt.Dimension(400, 80));

        jPanel10.setLayout(new java.awt.GridLayout(0, 2, 10, 0));

        jPanel11.setLayout(new java.awt.GridLayout(0, 2, 10, 0));

        jLabel2.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Employee Id:");
        jPanel11.add(jLabel2);

        txt_empId.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        txt_empId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_empId.setToolTipText("");
        txt_empId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_empIdActionPerformed(evt);
            }
        });
        txt_empId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_empIdKeyReleased(evt);
            }
        });
        jPanel11.add(txt_empId);

        jPanel10.add(jPanel11);

        jPanel12.setLayout(new java.awt.GridLayout(0, 2, 10, 0));

        btn_viewbyId.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        btn_viewbyId.setText("View by Id");
        btn_viewbyId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewbyIdActionPerformed(evt);
            }
        });
        jPanel12.add(btn_viewbyId);

        btn_viewAll.setFont(new java.awt.Font("Poppins Light", 1, 14)); // NOI18N
        btn_viewAll.setText("View All");
        btn_viewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_viewAllActionPerformed(evt);
            }
        });
        jPanel12.add(btn_viewAll);

        jPanel10.add(jPanel12);

        jPanel7.add(jPanel10);

        jPanel6.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        jPanel8.setPreferredSize(new java.awt.Dimension(5, 231));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel8, java.awt.BorderLayout.LINE_END);

        jPanel9.setPreferredSize(new java.awt.Dimension(5, 231));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel9, java.awt.BorderLayout.LINE_START);

        jPanel13.setPreferredSize(new java.awt.Dimension(456, 50));
        jPanel13.setLayout(new java.awt.GridLayout(0, 4, 10, 0));

        btn_add.setFont(new java.awt.Font("Poppins Light", 1, 12)); // NOI18N
        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel13.add(btn_add);

        btn_remove.setFont(new java.awt.Font("Poppins Light", 1, 12)); // NOI18N
        btn_remove.setText("Remove");
        btn_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeActionPerformed(evt);
            }
        });
        jPanel13.add(btn_remove);

        btn_update.setFont(new java.awt.Font("Poppins Light", 1, 12)); // NOI18N
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel13.add(btn_update);

        btn_clear.setFont(new java.awt.Font("Poppins Light", 1, 12)); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });
        jPanel13.add(btn_clear);

        jPanel6.add(jPanel13, java.awt.BorderLayout.PAGE_END);

        jPanel14.setLayout(new java.awt.GridLayout(0, 2, 10, 10));

        jLabel4.setFont(new java.awt.Font("Poppins Light", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Emp Id:");
        jPanel14.add(jLabel4);

        txt_empId1.setEditable(false);
        txt_empId1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txt_empId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_empId1ActionPerformed(evt);
            }
        });
        jPanel14.add(txt_empId1);

        jLabel5.setFont(new java.awt.Font("Poppins Light", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Name:");
        jPanel14.add(jLabel5);

        txt_name.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        jPanel14.add(txt_name);

        jLabel6.setFont(new java.awt.Font("Poppins Light", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Gender:");
        jPanel14.add(jLabel6);

        jPanel20.setLayout(new java.awt.GridLayout(0, 2, 10, 0));

        rbtn_male.setText("Male");
        rbtn_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_maleActionPerformed(evt);
            }
        });
        jPanel20.add(rbtn_male);

        rbtn_female.setText("Female");
        rbtn_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn_femaleActionPerformed(evt);
            }
        });
        jPanel20.add(rbtn_female);

        jPanel14.add(jPanel20);

        jLabel7.setFont(new java.awt.Font("Poppins Light", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Phone:");
        jPanel14.add(jLabel7);

        txt_phone.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txt_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phoneActionPerformed(evt);
            }
        });
        jPanel14.add(txt_phone);

        jLabel12.setFont(new java.awt.Font("Poppins Light", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Email:");
        jPanel14.add(jLabel12);

        txt_email.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        jPanel14.add(txt_email);

        jLabel8.setFont(new java.awt.Font("Poppins Light", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Address:");
        jPanel14.add(jLabel8);

        txt_address.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txt_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_addressActionPerformed(evt);
            }
        });
        jPanel14.add(txt_address);

        jLabel9.setFont(new java.awt.Font("Poppins Light", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Date of registration:");
        jPanel14.add(jLabel9);

        txt_regDate.setEditable(false);
        txt_regDate.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txt_regDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_regDateActionPerformed(evt);
            }
        });
        jPanel14.add(txt_regDate);

        jLabel10.setFont(new java.awt.Font("Poppins Light", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Username:");
        jPanel14.add(jLabel10);

        txt_username.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel14.add(txt_username);

        jLabel11.setFont(new java.awt.Font("Poppins Light", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Password:");
        jPanel14.add(jLabel11);

        txt_password.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jPanel14.add(txt_password);

        jPanel6.add(jPanel14, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6);

        jPanel15.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel15.add(jPanel16, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );

        jPanel15.add(jPanel17, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel15.add(jPanel18, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 538, Short.MAX_VALUE)
        );

        jPanel15.add(jPanel19, java.awt.BorderLayout.LINE_START);

        tbl_emp.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tbl_emp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee Id", "Name", "Gender", "Phone", "email", "Address", "Date", "Username", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_emp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_empMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_emp);

        jPanel15.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel15);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_empIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_empIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_empIdActionPerformed

    private void txt_empIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_empIdKeyReleased
        // TODO add your handling code here:
        getEmpRecordsById();
    }//GEN-LAST:event_txt_empIdKeyReleased

    private void btn_viewbyIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewbyIdActionPerformed
        // TODO add your handling code here:
        getEmpRecordsById();
    }//GEN-LAST:event_btn_viewbyIdActionPerformed

    private void btn_viewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_viewAllActionPerformed
        // TODO add your handling code here:
        getAllEmpRecords();
    }//GEN-LAST:event_btn_viewAllActionPerformed

    void getAllEmpRecords() {
        query = "SELECT * FROM `employee`";

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/carrentalmanagementsystem", "root", "root");
            pst = con.prepareStatement(query);

            rs = pst.executeQuery();
            model.setRowCount(0);

            while (rs.next()) {
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8), rs.getString(9)});
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "CRMS - Error Message", JOptionPane.ERROR_MESSAGE);

        }

    }

    void getEmpRecordsById() {
        query = "SELECT * FROM `employee` WHERE `emp_id`=?";
        String id = txt_empId.getText();
        if (id.equals("")) {
            JOptionPane.showMessageDialog(this, "Please input first the customer Id");
        } else {

            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/carrentalmanagementsystem", "root", "root");
                pst = con.prepareStatement(query);
                pst.setString(1, txt_empId.getText());

                rs = pst.executeQuery();
                model.setRowCount(0);

                while (rs.next()) {
                    model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7), rs.getString(8), rs.getString(9)});
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e, "Car Rental Services - Error Message", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();

            }
        }
    }


    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void txt_empId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_empId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_empId1ActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneActionPerformed

    private void txt_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_addressActionPerformed

    private void txt_regDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_regDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_regDateActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void tbl_empMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_empMouseClicked
        // TODO add your handling code here:
        int selectedRow = tbl_emp.getSelectedRow();

        txt_empId1.setText(model.getValueAt(selectedRow, 0).toString());
        txt_name.setText(model.getValueAt(selectedRow, 1).toString());

        String gender = model.getValueAt(selectedRow, 2).toString();
        if (gender.equals("M")) {
            rbtn_male.setSelected(true);
            rbtn_female.setSelected(false);
        } else if (gender.equals("F")) {
            rbtn_female.setSelected(true);
            rbtn_male.setSelected(false);
        }

        txt_phone.setText(model.getValueAt(selectedRow, 3).toString());
        txt_email.setText(model.getValueAt(selectedRow, 4).toString());
        txt_address.setText(model.getValueAt(selectedRow, 5).toString());
        txt_regDate.setText(model.getValueAt(selectedRow, 6).toString());
        txt_username.setText(model.getValueAt(selectedRow, 7).toString());
        txt_password.setText(model.getValueAt(selectedRow, 8).toString());


    }//GEN-LAST:event_tbl_empMouseClicked

    private void rbtn_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_maleActionPerformed
        // TODO add your handling code here:
        rbtn_male.setSelected(true);
        rbtn_female.setSelected(false);
    }//GEN-LAST:event_rbtn_maleActionPerformed

    private void rbtn_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn_femaleActionPerformed
        // TODO add your handling code here:

        rbtn_female.setSelected(true);
        rbtn_male.setSelected(false);
    }//GEN-LAST:event_rbtn_femaleActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void clear() {
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to clear the fields?");
        if (response == JOptionPane.YES_OPTION) {
            txt_empId1.setText("");
            txt_name.setText("");
            rbtn_male.setSelected(true);
            txt_phone.setText("");
            txt_email.setText("");
            txt_address.setText("");
            txt_username.setText("");
            txt_password.setText("");
        }

    }
    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:

        if (txt_name.getText().equals("")
                || txt_phone.getText().equals("")
                || txt_email.getText().equals("")
                || txt_address.getText().equals("")
                || txt_username.getText().equals("")
                || txt_password.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "One of the fields is empty", "CRMS - Error Messga", JOptionPane.ERROR_MESSAGE);
        } else {

            query = "INSERT INTO `employee`(`name`, `gender`, `phone`, `email`, `address`, `date`, `username`, `password`) VALUES (?,?,?,?,?,?,?,?)";
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/carrentalmanagementsystem", "root", "root");
                pst = con.prepareStatement(query);

                pst.setString(1, txt_name.getText());

                String gender = "";
                if (rbtn_male.isSelected()) {
                    gender = "M";
                } else if (rbtn_female.isSelected()) {
                    gender = "F";
                }
                pst.setString(2, gender);
                pst.setString(3, txt_phone.getText());
                pst.setString(4, txt_email.getText());
                pst.setString(5, txt_address.getText());
                pst.setString(6, cr.setDate() + " " + cr.setTime());
                pst.setString(7, txt_username.getText());
                pst.setString(8, txt_password.getText());

                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Employee Added Succesfully");
                getAllEmpRecords();
                clear();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex, "Car Rental Services - Error Message", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to remove the Employee?");
        if (response == JOptionPane.YES_OPTION) {
            query = "DELETE FROM `employee` WHERE `emp_id`=?";
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/carrentalmanagementsystem", "root", "root");
                pst = con.prepareStatement(query);

                pst.setString(1, txt_empId1.getText());

                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Employee Deleted Succesfully");
                getAllEmpRecords();
                clear();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex, "Car Rental Services - Error Message", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_removeActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:

        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to update the record?");
        if (response == JOptionPane.YES_OPTION) {
            query = "UPDATE `employee` SET `name`=?,`gender`=?,`phone`=?,`email`=?,`address`=?,`date`=?,`username`=?,`password`=? WHERE `emp_id`=?";
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/carrentalmanagementsystem", "root", "root");
                pst = con.prepareStatement(query);

                pst.setString(1, txt_name.getText());

                String gender = "";
                if (rbtn_male.isSelected()) {
                    gender = "M";
                } else if (rbtn_female.isSelected()) {
                    gender = "F";
                }
                pst.setString(2, gender);
                pst.setString(3, txt_phone.getText());
                pst.setString(4, txt_email.getText());
                pst.setString(5, txt_address.getText());
                pst.setString(6, cr.setDate() + " " + cr.setTime());
                pst.setString(7, txt_username.getText());
                pst.setString(8, txt_password.getText());
                pst.setString(9, txt_empId1.getText());

                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Employee Record Updated Succesfully");
                getAllEmpRecords();
                clear();

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex, "Car Rental Services - Error Message", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btn_updateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_remove;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_viewAll;
    private javax.swing.JButton btn_viewbyId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtn_female;
    private javax.swing.JRadioButton rbtn_male;
    private javax.swing.JTable tbl_emp;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_empId;
    private javax.swing.JTextField txt_empId1;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_regDate;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
