/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package carsrentalmanagementsystem;

import java.sql.DriverManager;
import javax.swing.JOptionPane;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ReturnRent extends javax.swing.JInternalFrame {

    String query;
    Connection con;
    PreparedStatement pst;
    ResultSet rs;

    DefaultTableModel model;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

    Date returnDate;
    Date expectedReturnDate;

    double fine = 5000;

    /**
     * Creates new form ReturnRent
     */
    public ReturnRent() {
        initComponents();

        CarRentals cr = new CarRentals();
        txt_returnDate.setText(cr.setDate());
        model = (DefaultTableModel) tbl_cust.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        txt_custId = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        txt_rentalId = new javax.swing.JTextField();
        txt_carId = new javax.swing.JTextField();
        txt_carName = new javax.swing.JTextField();
        txt_rentalDate = new javax.swing.JTextField();
        txt_expectedReturnDate = new javax.swing.JTextField();
        txt_returnDate = new javax.swing.JTextField();
        jPanel33 = new javax.swing.JPanel();
        txt_overdue = new javax.swing.JTextField();
        txt_fine = new javax.swing.JTextField();
        jPanel32 = new javax.swing.JPanel();
        btn_returnCar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_cust = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(869, 685));
        setPreferredSize(new java.awt.Dimension(869, 685));
        getContentPane().setLayout(new java.awt.BorderLayout(10, 0));

        jLabel1.setFont(new java.awt.Font("Poppins Light", 1, 24)); // NOI18N
        jLabel1.setText("Return Rented Vehicle");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(868, 10));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 857, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setPreferredSize(new java.awt.Dimension(10, 268));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel4.setPreferredSize(new java.awt.Dimension(10, 268));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 617, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);

        jPanel5.setLayout(new java.awt.GridLayout(0, 2, 10, 0));

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel8.setPreferredSize(new java.awt.Dimension(409, 10));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jPanel9.setPreferredSize(new java.awt.Dimension(10, 232));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel9, java.awt.BorderLayout.LINE_END);

        jPanel10.setPreferredSize(new java.awt.Dimension(10, 232));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel10, java.awt.BorderLayout.LINE_START);

        jPanel11.setPreferredSize(new java.awt.Dimension(409, 10));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel11, java.awt.BorderLayout.PAGE_END);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Manage Rentals", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins Light", 1, 12))); // NOI18N
        jPanel12.setLayout(new java.awt.BorderLayout(5, 5));

        txt_custId.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        txt_custId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_custId.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer Id", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins Light", 1, 12))); // NOI18N
        txt_custId.setPreferredSize(new java.awt.Dimension(150, 50));
        txt_custId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_custIdActionPerformed(evt);
            }
        });
        txt_custId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_custIdKeyReleased(evt);
            }
        });
        jPanel13.add(txt_custId);

        jPanel12.add(jPanel13, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel14, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel15, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 373, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel12.add(jPanel16, java.awt.BorderLayout.PAGE_END);

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "View", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins Light", 1, 12))); // NOI18N
        jPanel17.setPreferredSize(new java.awt.Dimension(888, 569));
        jPanel17.setLayout(new java.awt.BorderLayout());

        jPanel27.setPreferredSize(new java.awt.Dimension(5, 5));

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel27, java.awt.BorderLayout.PAGE_START);

        jPanel28.setPreferredSize(new java.awt.Dimension(5, 5));

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel28, java.awt.BorderLayout.LINE_END);

        jPanel29.setPreferredSize(new java.awt.Dimension(5, 5));

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel29, java.awt.BorderLayout.PAGE_END);

        jPanel30.setPreferredSize(new java.awt.Dimension(5, 5));

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );

        jPanel17.add(jPanel30, java.awt.BorderLayout.LINE_START);

        jPanel31.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        txt_rentalId.setEditable(false);
        txt_rentalId.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txt_rentalId.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_rentalId.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rental Id", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins Light", 1, 12))); // NOI18N
        jPanel31.add(txt_rentalId);

        txt_carId.setEditable(false);
        txt_carId.setFont(new java.awt.Font("Poppins Light", 0, 12)); // NOI18N
        txt_carId.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_carId.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Car Id", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins Light", 1, 12))); // NOI18N
        jPanel31.add(txt_carId);

        txt_carName.setEditable(false);
        txt_carName.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txt_carName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_carName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Car Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins Light", 1, 12))); // NOI18N
        jPanel31.add(txt_carName);

        txt_rentalDate.setEditable(false);
        txt_rentalDate.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txt_rentalDate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_rentalDate.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rental Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins Light", 1, 12))); // NOI18N
        jPanel31.add(txt_rentalDate);

        txt_expectedReturnDate.setEditable(false);
        txt_expectedReturnDate.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txt_expectedReturnDate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_expectedReturnDate.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Expected Return Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins Light", 1, 12))); // NOI18N
        jPanel31.add(txt_expectedReturnDate);

        txt_returnDate.setEditable(false);
        txt_returnDate.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txt_returnDate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_returnDate.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Return Date", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins Light", 1, 12))); // NOI18N
        jPanel31.add(txt_returnDate);

        jPanel33.setLayout(new java.awt.GridLayout(0, 2, 10, 0));

        txt_overdue.setEditable(false);
        txt_overdue.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txt_overdue.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_overdue.setText("0");
        txt_overdue.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Overdue", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins Light", 1, 12))); // NOI18N
        txt_overdue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_overdueActionPerformed(evt);
            }
        });
        jPanel33.add(txt_overdue);

        txt_fine.setEditable(false);
        txt_fine.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        txt_fine.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_fine.setText("0.0");
        txt_fine.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fine", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins Light", 1, 12))); // NOI18N
        jPanel33.add(txt_fine);

        jPanel31.add(jPanel33);

        jPanel32.setLayout(new java.awt.GridLayout());

        btn_returnCar.setFont(new java.awt.Font("Poppins Light", 1, 12)); // NOI18N
        btn_returnCar.setText("Return Car");
        btn_returnCar.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_returnCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_returnCarActionPerformed(evt);
            }
        });
        jPanel32.add(btn_returnCar);

        jPanel31.add(jPanel32);

        jPanel17.add(jPanel31, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel17, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel12, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel18.setPreferredSize(new java.awt.Dimension(5, 5));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel18, java.awt.BorderLayout.PAGE_START);

        jPanel19.setPreferredSize(new java.awt.Dimension(5, 5));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel19, java.awt.BorderLayout.LINE_START);

        jPanel20.setPreferredSize(new java.awt.Dimension(5, 5));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel20, java.awt.BorderLayout.LINE_END);

        jPanel21.setPreferredSize(new java.awt.Dimension(5, 5));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel21, java.awt.BorderLayout.PAGE_END);

        jPanel22.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Customer's Rented Vehicles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins Light", 1, 12))); // NOI18N
        jPanel22.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel22.add(jPanel23, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );

        jPanel22.add(jPanel24, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
        );

        jPanel22.add(jPanel25, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel22.add(jPanel26, java.awt.BorderLayout.PAGE_END);

        tbl_cust.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tbl_cust.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Rental Id", "Car Id", "Car Name", "Rental Date", "Expected Returned Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_cust.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_custMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_cust);

        jPanel22.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel22, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel7);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void getCustomers() {
        query = "SELECT `rental_id`, `car_id`, `car_name`, `date_of_rent`, `expected_return_date`, `return_date`  FROM `rentals` WHERE `cust_id`=? and `is_returned`=?";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/carrentalmanagementsystem", "root", "root");
            pst = con.prepareStatement(query);

            pst.setString(1, txt_custId.getText());
            pst.setString(2, Integer.toString(0));

            rs = pst.executeQuery();
            model.setRowCount(0);
            while (rs.next()) {
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)});

            }

            // JOptionPane.showMessageDialog(null, "Vehicle Rent Added Succesfully");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex, "Car Rental Services - Error Message", JOptionPane.ERROR_MESSAGE);
        }
    }


    private void txt_custIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_custIdKeyReleased
        // TODO add your handling code here:
        getCustomers();

    }//GEN-LAST:event_txt_custIdKeyReleased

    private void txt_custIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_custIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_custIdActionPerformed

    private void tbl_custMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_custMouseClicked
        // TODO add your handling code here:
        int selectedRow = tbl_cust.getSelectedRow();

        txt_rentalId.setText(model.getValueAt(selectedRow, 0).toString());
        txt_carId.setText(model.getValueAt(selectedRow, 1).toString());
        txt_carName.setText(model.getValueAt(selectedRow, 2).toString());
        txt_rentalDate.setText(model.getValueAt(selectedRow, 3).toString());
        txt_expectedReturnDate.setText(model.getValueAt(selectedRow, 4).toString());

        try {
            returnDate = sdf.parse(txt_returnDate.getText());
            expectedReturnDate = sdf.parse(txt_expectedReturnDate.getText());

        } catch (ParseException ex) {
            Logger.getLogger(ReturnRent.class.getName()).log(Level.SEVERE, null, ex);
        }

        Long dur = returnDate.getTime() - expectedReturnDate.getTime();
        Long duration = TimeUnit.DAYS.convert(dur, TimeUnit.MILLISECONDS);

        if (duration > 0) {
            txt_overdue.setText(Long.toString(duration));

            JOptionPane.showMessageDialog(this, "The customer has passed their expected return date");
            txt_fine.setText(Double.toString((double) fine * duration));
        } else if (duration <= 0) {
            txt_overdue.setText(Integer.toString(0));

            txt_fine.setText(Double.toString((double) fine * 0));
        }


    }//GEN-LAST:event_tbl_custMouseClicked

    private void btn_returnCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_returnCarActionPerformed
        // TODO add your handling code here:
        String query = "UPDATE `rentals` SET `return_date`=?,`is_returned`=?,`overdue`=?,`fine`=? WHERE `car_id`=?";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/carrentalmanagementsystem", "root", "root");
            pst = con.prepareStatement(query);
            pst.setString(1, txt_returnDate.getText());
            pst.setString(2, Integer.toString(1));
            pst.setString(3, txt_overdue.getText());
            pst.setString(4, txt_fine.getText());

            pst.setString(5, txt_carId.getText());

            pst.executeUpdate();


        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex, "CRMS - Error Message", JOptionPane.ERROR_MESSAGE);
        }

        String queryCar = "UPDATE `car` SET `isPresent`=? WHERE `car_id`=?";
        try {
            Class.forName("com.mysql.jdbc.Driver");
             con = DriverManager.getConnection("jdbc:mysql://localhost:3306/carrentalmanagementsystem", "root", "root");
             pst = con.prepareStatement(queryCar);
            pst.setString(1, Integer.toString(1));

            pst.setString(2, txt_carId.getText());

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Vehicle Return  Succesfully");
                        getCustomers();

            getCustomers();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex, "CRMS - Error Message", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();

        }

    }//GEN-LAST:event_btn_returnCarActionPerformed

    private void txt_overdueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_overdueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_overdueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_returnCar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_cust;
    private javax.swing.JTextField txt_carId;
    private javax.swing.JTextField txt_carName;
    private javax.swing.JTextField txt_custId;
    private javax.swing.JTextField txt_expectedReturnDate;
    private javax.swing.JTextField txt_fine;
    private javax.swing.JTextField txt_overdue;
    private javax.swing.JTextField txt_rentalDate;
    private javax.swing.JTextField txt_rentalId;
    private javax.swing.JTextField txt_returnDate;
    // End of variables declaration//GEN-END:variables
}
